"""create qa_table

Revision ID: 05fba458ec45
Revises: 
Create Date: 2026-03-26 09:38:46.505570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05fba458ec45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Create qa_table if it doesn't exist yet
    if 'qa_table' not in tables:
        op.create_table('qa_table',
            sa.Column('question_id', sa.String(), nullable=False),
            sa.Column('question_text', sa.Text(), nullable=False),
            sa.Column('answer_text', sa.Text(), nullable=True),
            sa.Column('subject', sa.String(), nullable=True),
            sa.Column('difficulty', sa.String(), nullable=True),
            sa.Column('bloom_level', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('question_id')
        )

    # Guard: only drop the old LangGraph 'store' tables if they actually exist.
    # On a fresh Railway DB these tables were never created, so skipping is correct.
    if 'store' in tables:
        # Drop indexes safely
        indexes = [idx['name'] for idx in inspector.get_indexes('store')]
        if 'idx_store_expires_at' in indexes:
            op.drop_index('idx_store_expires_at', table_name='store')
        if 'store_prefix_idx' in indexes:
            op.drop_index('store_prefix_idx', table_name='store')
        op.drop_table('store')

    if 'store_migrations' in tables:
        op.drop_table('store_migrations')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.drop_table('qa_table')
    # ### end Alembic commands ###
