"""create qa_table

Revision ID: 82d327259c82
Revises: 05fba458ec45
Create Date: 2026-03-26 09:59:36.563391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82d327259c82'
down_revision: Union[str, Sequence[str], None] = '05fba458ec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('qa_table')]
    
    if 'topic_tags' not in columns:
        op.add_column('qa_table', sa.Column('topic_tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_table', 'topic_tags')
    # ### end Alembic commands ###
